// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlertToCareAPI.Migrations
{
    [DbContext(typeof(IcuContext))]
    partial class IcuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Entities.Beds", b =>
                {
                    b.Property<string>("BedId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("BedStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IcuId")
                        .HasColumnType("TEXT");

                    b.HasKey("BedId");

                    b.ToTable("Beds");
                });

            modelBuilder.Entity("Entities.ICU", b =>
                {
                    b.Property<string>("IcuId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BedIdPrefix")
                        .HasColumnType("TEXT");

                    b.Property<int>("BedsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Layout")
                        .HasColumnType("TEXT");

                    b.HasKey("IcuId");

                    b.ToTable("ICUs");
                });

            modelBuilder.Entity("Entities.Patient", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ICUId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.HasIndex("ICUId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Entities.PatientAddress", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pincode")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.ToTable("PatientAddress");
                });

            modelBuilder.Entity("Entities.Vitals", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Bpm")
                        .HasColumnType("REAL");

                    b.Property<float>("RespRate")
                        .HasColumnType("REAL");

                    b.Property<float>("Spo2")
                        .HasColumnType("REAL");

                    b.HasKey("PatientId");

                    b.ToTable("Vitals");
                });

            modelBuilder.Entity("Entities.Patient", b =>
                {
                    b.HasOne("Entities.ICU", null)
                        .WithMany("Patients")
                        .HasForeignKey("ICUId");
                });

            modelBuilder.Entity("Entities.PatientAddress", b =>
                {
                    b.HasOne("Entities.Patient", null)
                        .WithOne("Address")
                        .HasForeignKey("Entities.PatientAddress", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Vitals", b =>
                {
                    b.HasOne("Entities.Patient", null)
                        .WithOne("Vitals")
                        .HasForeignKey("Entities.Vitals", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
